### ISSUE TITLE
can't encrypt :-(

### ISSUE THREAD

**Issue by tansaku** [dokku/dokku-letsencrypt#112]
```
→ ssh dokku@agileventures.eastus.cloudapp.azure.com letsencrypt asyncvoter-production -v
=====> Let's Encrypt asyncvoter-production
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:398e9173f8e9662df66cb6d0dfa6c6ac07f1e3d65b7994177d487d36eb9b10be
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for asyncvoter-production...
-----> Getting letsencrypt certificate for asyncvoter-production...
        - Domain 'production.asyncvoter.agileventures.org'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2017-05-19 16:47:20,070:INFO:__main__:1211: Generating new account key
Traceback (most recent call last):
  File "/simp_le-master/simp_le.py", line 1401, in main
    return main_with_exceptions(cli_args)
  File "/simp_le-master/simp_le.py", line 1386, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/simp_le-master/simp_le.py", line 1282, in persist_new_data
    client = registered_client(args, existing_data.account_key)
  File "/simp_le-master/simp_le.py", line 1224, in registered_client
    client = acme_client.Client(args.server, key=key, net=net)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 624, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 571, in _check_response
    raise errors.ClientError(response)
ClientError: <Response [504]>

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for asyncvoter-production...
       done

```
had this working before, but now I just get this 504 ...

**Comment by tansaku** [comment]
we're on: letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates

**Comment by joshmanders** [comment]
Lets encrypt is having issues. https://letsencrypt.status.io/?170519

**Comment by tansaku** [comment]
thanks @joshmanders that was it :-)
