### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by dblock** [dokku/dokku-letsencrypt#149]
What do I do?

This is with 0.8.8.

```
root@dblock-plum:~# dokku letsencrypt whatever-bot
=====> Let's Encrypt whatever-bot
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:95681f7cd659f23f451738121df9efe42ffc919e93a969781c40e936258fea72
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for whatever-bot...
-----> Getting letsencrypt certificate for whatever-bot...
        - Domain 'whatever.playplay.io'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2018-03-29 22:02:59,945:INFO:__main__:1211: Generating new account key
2018-03-29 22:03:02,788:INFO:__main__:1305: whatever.playplay.io was successfully self-verified
2018-03-29 22:03:03,061:INFO:__main__:1313: Generating new certificate private key
Traceback (most recent call last):
  File "/simp_le-master/simp_le.py", line 1401, in main
    return main_with_exceptions(cli_args)
  File "/simp_le-master/simp_le.py", line 1386, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/simp_le-master/simp_le.py", line 1316, in persist_new_data
    certr = get_certr(client, csr, authorizations)
  File "/simp_le-master/simp_le.py", line 1257, in get_certr
    ', '.join(authzr.uri for _, authzr in error.exhausted)
  File "/simp_le-master/simp_le.py", line 1257, in <genexpr>
    ', '.join(authzr.uri for _, authzr in error.exhausted)
ValueError: too many values to unpack

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for whatever-bot...
       done
```

**Comment by dblock** [comment]
It suddenly started working ...

**Comment by josegonzalez** [comment]
Might have been a temp error on LE end.
