### ISSUE TITLE
Trying to generate a new cert, consistently receiving timeout errors

### ISSUE THREAD

**Issue by dougbarrett** [dokku/dokku-letsencrypt#197]
Here is the full output from when the command was entered to the final part of the error message:

```
dokku letsencrypt projectconnect.us -v
=====> Let's Encrypt projectconnect.us
-----> Updating letsencrypt docker image...
0.1.0: Pulling from dokku/letsencrypt
Digest: sha256:af5f8529c407645e97821ad28eba328f4c59b83b2141334f899303c49fc07823
Status: Image is up to date for dokku/letsencrypt:0.1.0
       Done updating
-----> Enabling ACME proxy for projectconnect.us...
[ ok ] Reloading nginx configuration (via systemctl): nginx.service.
-----> Getting letsencrypt certificate for projectconnect.us...
        - Domain 'projectconnect.us'
        - Domain 'moorparktech.org'
        - Domain '*.projectconnect.us'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2020-03-20 05:56:17,665:INFO:__main__:1317: Generating new account key
2020-03-20 05:56:18,349:INFO:__main__:1343: By using simp_le, you implicitly agree to the CA's terms of service: https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
2020-03-20 05:56:18,646:INFO:__main__:1406: Generating new certificate private key
Traceback (most recent call last):
  File "/simp_le/simp_le.py", line 1551, in main
    return main_with_exceptions(cli_args)
  File "/simp_le/simp_le.py", line 1535, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/simp_le/simp_le.py", line 1435, in persist_new_data
    order = finalize_order(client, order)
  File "/simp_le/simp_le.py", line 1362, in finalize_order
    finalized_order = client.poll_and_finalize(order)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 697, in poll_and_finalize
    orderr = self.poll_authorizations(orderr, deadline)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 713, in poll_authorizations
    raise errors.TimeoutError()
TimeoutError

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for projectconnect.us...
[ ok ] Reloading nginx configuration (via systemctl): nginx.service.
       done

```

I'm wondering if it has something to do with the wildcard domain I'm trying to add?

**Comment by johnniehard** [comment]
I don't know if it has anything to do with the wildcard domain, but I found this issue because I was also consistently encountering timeout errors for a specific application.
I solved it by removing the `/home/dokku/<app>/letsencrypt` folder. Must have been some cruft laying around from a previous failed attempt.

**Comment by josegonzalez** [comment]
Might be the above issue.

If anyone still sees this, please open a new issue so we can investigate.
